version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: nest.dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/db
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=db
    depends_on:
      - mongodb
    networks:
      - app-network

  mariadb:
    image: mariadb:latest
    ports:
      - "3555:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db
    
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: